name: Cross-Platform Script Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make script executable
        run: chmod +x ./unix.sh

      - name: Run help command
        run: ./unix.sh --help

      - name: Run script to change time (requires sudo)
        run: sudo ./unix.sh 60

      - name: Run script to change time with sync off (requires sudo)
        run: sudo ./unix.sh 60 -s

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make script executable
        run: chmod +x ./mac.sh

      - name: Run help command
        run: ./mac.sh --help

      - name: Run script to change time (requires sudo)
        run: sudo ./mac.sh 60

      - name: Run script to change time with sync off (requires sudo)
        run: sudo ./mac.sh 60 -s

  test-windows-cmd:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run CMD script with --help
        run: |
          cmd /c cmd.bat --help

      - name: Run CMD script with time change
        run: |
          cmd /c cmd.bat 60

      - name: Run CMD script with time change and sync off
        run: |
          cmd /c cmd.bat 60 -s

  test-windows-powershell:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test --help for PowerShell
        run: powershell.exe -File ./power-shell.ps1 --help
        continue-on-error: false

      - name: Test time change for PowerShell
        run: |
          powershell.exe -File ./power-shell.ps1 60
        continue-on-error: false

      - name: Test time change with sync off for PowerShell
        run: |
          powershell.exe -File ./power-shell.ps1 60 -s
        continue-on-error: false
