name: Test Windows CMD

on:
  push:
    paths:
      - "cmd.bat"
  pull_request:
    paths:
      - "cmd.bat"

jobs:
  test-windows-cmd:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run CMD script with --help
        run: |
          cmd /c cmd.bat --help

      - name: Run CMD script with time change
        run: |
          cmd /c cmd.bat 60

      - name: Run CMD script with time change and sync off
        run: |
          cmd /c cmd.bat 60 -s
