name: Cross-Platform Script Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test --help for Linux
        run: |
          chmod +x ./unix.sh
          ./unix.sh --help
        continue-on-error: false

      - name: Test time change for Linux
        run: |
          sudo ./unix.sh 60
        continue-on-error: false

      - name: Test time change with sync off for Linux
        run: |
          sudo ./unix.sh 60 -s
        continue-on-error: false

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test --help for macOS
        run: |
          chmod +x ./mac.sh
          ./mac.sh --help
        continue-on-error: false

      - name: Test time change for macOS
        run: |
          sudo ./mac.sh 60
        continue-on-error: false

      - name: Test time change with sync off for macOS
        run: |
          sudo ./mac.sh 60 -s
        continue-on-error: false

  test-windows-cmd:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test --help for CMD
        run: ./cmd.bat --help
        continue-on-error: false

      - name: Test time change for CMD
        run: |
          echo Running time change test...
          ./cmd.bat 60
        continue-on-error: false

      - name: Test time change with sync off for CMD
        run: |
          echo Running time change with sync off test...
          ./cmd.bat 60 -s
        continue-on-error: false

  test-windows-powershell:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test --help for PowerShell
        run: powershell.exe -File ./power-shell.ps1 --help
        continue-on-error: false

      - name: Test time change for PowerShell
        run: |
          powershell.exe -File ./power-shell.ps1 60
        continue-on-error: false

      - name: Test time change with sync off for PowerShell
        run: |
          powershell.exe -File ./power-shell.ps1 60 -s
        continue-on-error: false
